version: '3.4'
services:
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"

  database:
    image: "mysql:latest"
    ports:
      - "3306:3306"
    

  backend:
    build: .
    ports:
      - "3000:3000" 
    depends_on:
      - redis
      - database
    environment: 
      DB_HOST: database
      DB_PORT: 3306
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_TTL: 300